name: "Build Golang and Deploy Terraform"

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  id-token: write
  contents: read

jobs:
  build:
    name: "Build Golang"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5

      - run: go build -o bootstrap main.go

      - uses: actions/upload-artifact@v4
        with:
          path: bootstrap
          retention-days: 1

  terraform:
    name: "Deploy Terraform"
    runs-on: ubuntu-latest
    needs: build
    env:
      tf_actions_working_dir: 'terraform'
    defaults:
      run:
        working-directory: ${{ env.tf_actions_working_dir }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download Artifact 
        uses: actions/download-artifact@v4
        with:
          name: artifact
          path: terraform

      - name: Zip function to upload to AWS Lambda
        run: zip main.zip bootstrap && rm -rf bootstrap && ls -R

      - name: Load secret
        uses: 1password/load-secrets-action@v1
        with:
          export-env: true
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          AWS_ROLE_TO_ASSUME: op://Service Account Vault/IAM Role DeployVassopoliBotTelegramAdapter/credential
          TF_API_TOKEN: op://Service Account Vault/Terraform Team Token/credential
          TF_VAR_app_telegram_token: op://Service Account Vault/VassopoliBot Telegram Token/credential

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.AWS_ROLE_TO_ASSUME }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          cli_config_credentials_token: ${{ env.TF_API_TOKEN }}

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check
        continue-on-error: true

      - name: Terraform Init
        id: init
        run: terraform init 
      
      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color -input=false
        continue-on-error: false

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -auto-approve -input=false